import{useEffect,useState}from'react';import{ANTES,CHARMS,CATEGORIES,bestCategory,buy,doRoll,evaluate,newRun,nextAnte,refresh,scoreHand,scoreTurn,type Category,type RunState}from'./engine';import{isActiveRun,parseSavedRun}from'./save';
const SAVE='ante-up-dice.save.v1',HIGH='ante-up-dice.high';
const PIPS=[[50,50],[27,27],[73,73],[27,73],[73,27],[27,50],[73,50]];
function Die({value,held,onClick,index}:{value:number;held:boolean;onClick:()=>void;index:number}){const dots:Record<number,number[]>={1:[0],2:[1,2],3:[1,0,2],4:[1,4,3,2],5:[1,4,0,3,2],6:[1,5,4,3,6,2]};return <button className={'die '+(held?'held':'')} onClick={onClick} aria-label={`Die ${index+1}: ${value}, ${held?'held':'not held'}`} aria-pressed={held}>{(dots[value]??[]).map((p,i)=><i key={i} style={{left:`${PIPS[p]?.[0]}%`,top:`${PIPS[p]?.[1]}%`}}/>)}<span>{held?'HELD':'HOLD'}</span></button>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="scrim" role="presentation" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><button className="close" onClick={onClose} aria-label="Close">×</button><h2 id="modal-title">{title}</h2>{children}</section></div>}
async function tone(enabled:boolean){if(!enabled)return;const AudioContext=window.AudioContext;if(typeof AudioContext!=='function')return;let context:AudioContext|null=null;let oscillator:OscillatorNode|null=null;let gain:GainNode|null=null;try{context=new AudioContext();if(context.state==='suspended')await context.resume();oscillator=context.createOscillator();gain=context.createGain();oscillator.frequency.value=220;gain.gain.setValueAtTime(.04,context.currentTime);gain.gain.exponentialRampToValueAtTime(.001,context.currentTime+.09);oscillator.connect(gain).connect(context.destination);oscillator.start();oscillator.stop(context.currentTime+.1);await new Promise<void>(resolve=>{if(oscillator)oscillator.onended=()=>resolve();else resolve()})}catch{/* Sound is optional; browser audio policy must never interrupt play. */}finally{try{oscillator?.disconnect()}catch{/* already disconnected */}try{gain?.disconnect()}catch{/* already disconnected */}if(context)try{await context.close()}catch{/* already closed or blocked */}}}
function App(){const [run,setRun]=useState<RunState|null>(null);const [help,setHelp]=useState(false);const [sound,setSound]=useState(true);const [selected,setSelected]=useState<Category|null>(null);const [notice,setNotice]=useState('');
 const saved=run===null?parseSavedRun(localStorage.getItem(SAVE)):null;const savedRun=saved&&isActiveRun(saved)?saved:null;if(run===null&&!savedRun&&localStorage.getItem(SAVE)!==null)localStorage.removeItem(SAVE);
 useEffect(()=>{if(!run)return;if(isActiveRun(run))localStorage.setItem(SAVE,JSON.stringify(run));else localStorage.removeItem(SAVE)},[run]);
 const valid=run?.dice.length===5?evaluate(run.dice):[];const best=run?.dice.length===5?bestCategory(run.dice):null;const pick=selected&&valid.includes(selected)?selected:best;const preview=run&&pick?scoreHand(run.dice,pick,run.charms,run.cash,run.rolls):null;
 const act=(fn:(r:RunState)=>RunState)=>{if(run){void tone(sound);setRun(fn(run));setSelected(null)}};
 const high=Number(localStorage.getItem(HIGH)??0);useEffect(()=>{if(run&&run.score>high)localStorage.setItem(HIGH,String(run.score))},[run,high]);
 const startNew=()=>{if(savedRun&&!confirm('Start a new run? Your current run will be overwritten.'))return;setRun(newRun())};
 if(!run)return <main className="welcome"><div className="brandmark">⚄</div><p className="eyebrow">A tabletop roguelike</p><h1>ANTE UP<br/><em>DICE</em></h1><p>Build bold hands. Collect peculiar charms. Outscore eight rising tables.</p>{savedRun&&<button className="primary" onClick={()=>setRun(savedRun)}>Continue run</button>}<button className={savedRun?'':'primary'} onClick={startNew}>Start new run</button><button onClick={()=>setHelp(true)}>Rules & accessibility</button>{help&&<Help onClose={()=>setHelp(false)}/>}<small>Local high score · {high.toLocaleString()}</small></main>;
 if(run.status==='won'||run.status==='lost')return <main className="end"><p className="eyebrow">Run complete</p><h1>{run.status==='won'?'The table is yours':'The lights go dim'}</h1><p>{run.status==='won'?'You cleared every ante. A legendary night.':'The target held. Take what you learned to the next table.'}</p><div className="summary"><b>{run.score.toLocaleString()}</b><span>final table score</span><b>Ante {run.ante}</b><span>reached</span><b>{run.charms.length}</b><span>charms owned</span></div><button className="primary" onClick={()=>setRun(newRun())}>Deal a new run</button><button onClick={()=>setRun(null)}>Main menu</button></main>;
 if(run.status==='shop')return <main className="shop"><header><div><p className="eyebrow">Ante {run.ante} cleared</p><h1>The Backroom</h1></div><div className="money">${run.cash}</div></header><p>Choose lasting charms. You may carry five.</p><div className="wares">{run.shop.map(id=>{const c=CHARMS.find(x=>x.id===id)!;return <article className={`charm ${c.rarity.toLowerCase()}`} key={id}><span>{c.rarity}</span><div className="sigil">✦</div><h2>{c.name}</h2><p>{c.text}</p><button disabled={run.cash<c.cost||run.charms.length>=5} onClick={()=>act(r=>buy(r,id))}>Buy · ${c.cost}</button></article>})}</div><div className="shop-actions"><button disabled={run.cash<2+run.refreshes} onClick={()=>act(refresh)}>Refresh · ${2+run.refreshes}</button><button className="primary" onClick={()=>act(nextAnte)}>Enter ante {run.ante+1} →</button></div></main>;
 return <main className="table"><aside className="rail"><div className="plaque"><p className="eyebrow">Ante {run.ante} of {ANTES.length}</p><h2>Table target</h2><strong>{run.target.toLocaleString()}</strong><meter min="0" max={run.target} value={run.score}/><span>{run.score.toLocaleString()} banked</span></div><div className="stats"><span>Hands<b>{run.hands}</b></span><span>Rolls<b>{run.rolls}</b></span><span>Cash<b>${run.cash}</b></span><span>Best<b>{high}</b></span></div><button onClick={()=>setHelp(true)}>Rules / settings</button><button onClick={()=>setRun(null)}>Main menu</button></aside>
 <section className="board"><header className="top"><div><p className="eyebrow">Ante Up Dice</p><h1>Make your hand</h1></div><div className="slots" aria-label="Equipped charms">{run.charms.map(id=>{const c=CHARMS.find(x=>x.id===id)!;return <div className="mini" title={c.text} key={id}><i>✦</i><b>{c.name}</b><small>{c.text}</small></div>})}{[...Array(5-run.charms.length)].map((_,i)=><div className="empty" key={i}>◇</div>)}</div></header>
 <div className={'dice '+(notice?'scoring':'')}>{run.dice.length?run.dice.map((d,i)=><Die key={i} value={d} index={i} held={run.held[i]??false} onClick={()=>setRun({...run,held:run.held.map((h,j)=>j===i?!h:h)})}/>):<p className="ready">The dice are waiting.</p>}</div>
 <div className="tray" aria-label="Scoring categories">{(Object.keys(CATEGORIES) as Category[]).map(id=>{const c=CATEGORIES[id],ok=valid.includes(id);return <button key={id} className={pick===id?'active':''} disabled={run.dice.length>0&&!ok} onClick={()=>ok&&setSelected(id)}><b>{c.name}</b><small>{c.base} × {c.mult}</small></button>})}</div>
 <div className="scorebar"><div>{preview?<><span>{CATEGORIES[preview.category].name}</span><b>{preview.base} chips</b><i>×</i><b>{preview.mult} mult</b><i>=</i><strong>{preview.chips}</strong></>:<span>Roll to reveal a scoring hand</span>}</div>{run.dice.length===0||run.rolls>0?<button className="primary roll" onClick={()=>act(doRoll)}>{run.dice.length?'Reroll loose dice':'Roll dice'} <small>{run.rolls} left</small></button>:null}{run.dice.length===5&&<button className="primary score" onClick={()=>{if(preview){setNotice(`+${preview.chips}`);setTimeout(()=>setNotice(''),500)}act(r=>scoreTurn(r,pick??undefined))}}>Score hand <small>{preview?.chips??0} chips</small></button>}</div>{notice&&<div className="burst">{notice}</div>}</section>
 {help&&<Help onClose={()=>setHelp(false)} sound={sound} setSound={setSound}/>}</main>}
function Help({onClose,sound,setSound}:{onClose:()=>void;sound?:boolean;setSound?:(x:boolean)=>void}){return <Modal title="How to play" onClose={onClose}><p>Clear each table target before your four scoring hands run out. Every hand gets three rolls. Click dice to hold them, reroll the rest, then choose any highlighted category and score.</p><h3>Scoring table</h3><div className="rules">{Object.entries(CATEGORIES).map(([id,c])=><div key={id}><b>{c.name}</b><span>{c.help}</span><strong>{c.base} × {c.mult}</strong></div>)}</div><p>Charms apply in their listed order and show deterministic bonuses. Buy them between antes; refreshes grow more expensive.</p>{setSound&&<label className="toggle"><input type="checkbox" checked={sound} onChange={e=>setSound(e.target.checked)}/> Generated sound cues</label>}<p><small>Keyboard: Tab to move, Enter or Space to activate. Held dice are announced and marked with both text and a gold frame.</small></p></Modal>}
export default App;
