export type Pip=1|2|3|4|5|6;
export type Category='chance'|'pair'|'twoPair'|'threeKind'|'smallStraight'|'largeStraight'|'fullHouse'|'fourKind'|'fiveKind';
export type Rarity='Common'|'Uncommon'|'Rare';
export interface Charm {id:string;name:string;rarity:Rarity;cost:number;text:string}
export interface Score {category:Category;base:number;mult:number;chips:number;triggers:string[]}
export interface RunState {version:1;seed:number;ante:number;score:number;target:number;cash:number;hands:number;rolls:number;dice:Pip[];held:boolean[];charms:string[];shop:string[];refreshes:number;status:'playing'|'shop'|'won'|'lost'}

export const CATEGORIES:Record<Category,{name:string;base:number;mult:number;help:string}>={
 chance:{name:'Open Table',base:8,mult:1,help:'Any five dice'},pair:{name:'One Pair',base:12,mult:2,help:'Two matching dice'},twoPair:{name:'Two Pair',base:20,mult:2,help:'Two different pairs'},threeKind:{name:'Three of a Kind',base:24,mult:3,help:'Three matching dice'},smallStraight:{name:'Short Run',base:28,mult:3,help:'Four consecutive values'},largeStraight:{name:'Grand Run',base:38,mult:4,help:'Five consecutive values'},fullHouse:{name:'Full House',base:35,mult:4,help:'Three matching plus a pair'},fourKind:{name:'Four of a Kind',base:48,mult:5,help:'Four matching dice'},fiveKind:{name:'Five of a Kind',base:70,mult:7,help:'Five matching dice'}
};
export const ANTES=[{target:120,reward:7},{target:260,reward:9},{target:480,reward:11},{target:760,reward:13},{target:1120,reward:15},{target:1580,reward:18},{target:2150,reward:21},{target:2900,reward:25}];
export const CHARMS:Charm[]=[
 {id:'brass-tack',name:'Brass Tack',rarity:'Common',cost:4,text:'+8 base chips on a Pair.'},{id:'even-keel',name:'Even Keel',rarity:'Common',cost:4,text:'+2 base chips for each even die.'},{id:'odd-job',name:'Odd Job',rarity:'Common',cost:4,text:'+2 base chips for each odd die.'},{id:'pocket-change',name:'Pocket Change',rarity:'Common',cost:5,text:'+1 multiplier when cash is $5 or less.'},
 {id:'short-fuse',name:'Short Fuse',rarity:'Uncommon',cost:7,text:'+2 multiplier on the final roll.'},{id:'sixth-sense',name:'Sixth Sense',rarity:'Uncommon',cost:7,text:'+1 multiplier for every 6.'},{id:'low-road',name:'Low Road',rarity:'Uncommon',cost:7,text:'+12 base chips if all dice are 4 or lower.'},{id:'second-wind',name:'Second Wind',rarity:'Uncommon',cost:8,text:'+2 multiplier with exactly two pairs.'},
 {id:'velvet-rope',name:'Velvet Rope',rarity:'Rare',cost:11,text:'Double base chips for a straight.'},{id:'loaded-ledger',name:'Loaded Ledger',rarity:'Rare',cost:12,text:'+1 multiplier per $10 held.'},{id:'echo-chamber',name:'Echo Chamber',rarity:'Rare',cost:12,text:'+3 multiplier for four or five of a kind.'},{id:'house-lantern',name:'House Lantern',rarity:'Rare',cost:13,text:'+25 base chips when no 1 appears.'}
];
export function rng(seed:number):[number,number]{let x=seed|0;x^=x<<13;x^=x>>>17;x^=x<<5;return[(x>>>0)/4294967296,x>>>0]}
export function rollDice(seed:number,current:Pip[]=[],held:boolean[]=[]):{dice:Pip[];seed:number}{let s=seed;const dice:Array<Pip>=[];for(let i=0;i<5;i++){const existing=current[i];if(held[i]&&existing!==undefined)dice.push(existing);else{const [n,next]=rng(s);s=next;dice.push((Math.floor(n*6)+1) as Pip)}}return{dice,seed:s}}
export function evaluate(dice:Pip[]):Category[]{const c=new Map<number,number>();dice.forEach(d=>c.set(d,(c.get(d)??0)+1));const counts=[...c.values()].sort((a,b)=>b-a);const uniq=[...c.keys()].sort();const consecutive=(n:number)=>{for(let i=0;i<=uniq.length-n;i++)if(uniq.slice(i,i+n).every((v,j,a)=>j===0||v===(a[j-1]??0)+1))return true;return false};const out:Category[]=['chance'];if(counts[0]===5)out.push('fiveKind');if(counts[0]===4)out.push('fourKind');if(counts[0]===3&&counts[1]===2)out.push('fullHouse');if(consecutive(5))out.push('largeStraight');if(consecutive(4))out.push('smallStraight');if(counts[0]===3)out.push('threeKind');if(counts.filter(x=>x===2).length>=2)out.push('twoPair');if(counts.some(x=>x===2))out.push('pair');return out}
export function bestCategory(d:Pip[]):Category{return evaluate(d).sort((a,b)=>CATEGORIES[b].base*CATEGORIES[b].mult-CATEGORIES[a].base*CATEGORIES[a].mult)[0]??'chance'}
export function scoreHand(dice:Pip[],category:Category,charmIds:string[],cash:number,rolls:number):Score{let {base,mult}=CATEGORIES[category];const triggers:string[]=[];const hit=(id:string,fn:()=>void)=>{if(charmIds.includes(id)){fn();triggers.push(CHARMS.find(c=>c.id===id)?.name??id)}};hit('brass-tack',()=>{if(category==='pair')base+=8});hit('even-keel',()=>base+=dice.filter(x=>x%2===0).length*2);hit('odd-job',()=>base+=dice.filter(x=>x%2===1).length*2);hit('pocket-change',()=>{if(cash<=5)mult++});hit('short-fuse',()=>{if(rolls===0)mult+=2});hit('sixth-sense',()=>mult+=dice.filter(x=>x===6).length);hit('low-road',()=>{if(dice.every(x=>x<=4))base+=12});hit('second-wind',()=>{if(category==='twoPair')mult+=2});hit('velvet-rope',()=>{if(category==='smallStraight'||category==='largeStraight')base*=2});hit('loaded-ledger',()=>mult+=Math.floor(cash/10));hit('echo-chamber',()=>{if(category==='fourKind'||category==='fiveKind')mult+=3});hit('house-lantern',()=>{if(!dice.includes(1))base+=25});return{category,base,mult,chips:base*mult,triggers}}
function shop(seed:number,owned:string[]):[string[],number]{const pool=CHARMS.filter(c=>!owned.includes(c.id));const result:string[]=[];let s=seed;while(result.length<Math.min(3,pool.length)){const[n,next]=rng(s);s=next;const id=pool[Math.floor(n*pool.length)]?.id;if(id&&!result.includes(id))result.push(id)}return[result,s]}
export function newRun(seed=Date.now()>>>0):RunState{return{version:1,seed,ante:1,score:0,target:ANTES[0]!.target,cash:5,hands:4,rolls:3,dice:[],held:[false,false,false,false,false],charms:[],shop:[],refreshes:0,status:'playing'}}
export function doRoll(s:RunState):RunState{if(s.status!=='playing'||s.rolls<=0)return s;const r=rollDice(s.seed,s.dice,s.held);return{...s,...r,rolls:s.rolls-1}}
export function scoreTurn(s:RunState,category=bestCategory(s.dice)):RunState{if(s.status!=='playing'||s.dice.length!==5||!evaluate(s.dice).includes(category))return s;const gained=scoreHand(s.dice,category,s.charms,s.cash,s.rolls).chips;const total=s.score+gained;if(total>=s.target){const a=ANTES[s.ante-1]!;const [items,seed]=shop(s.seed,s.charms);return{...s,seed,score:total,cash:s.cash+a.reward,shop:items,status:s.ante===ANTES.length?'won':'shop'}}const hands=s.hands-1;return{...s,score:total,hands,rolls:3,dice:[],held:s.held.map(()=>false),status:hands<=0?'lost':'playing'}}
export function buy(s:RunState,id:string):RunState{const c=CHARMS.find(x=>x.id===id);if(!c||s.status!=='shop'||s.cash<c.cost||s.charms.length>=5||!s.shop.includes(id))return s;return{...s,cash:s.cash-c.cost,charms:[...s.charms,id],shop:s.shop.filter(x=>x!==id)}}
export function refresh(s:RunState):RunState{const cost=2+s.refreshes;if(s.status!=='shop'||s.cash<cost)return s;const [items,seed]=shop(s.seed,s.charms);return{...s,cash:s.cash-cost,seed,shop:items,refreshes:s.refreshes+1}}
export function nextAnte(s:RunState):RunState{if(s.status!=='shop')return s;const ante=s.ante+1;return{...s,ante,target:ANTES[ante-1]!.target,score:0,hands:4,rolls:3,dice:[],held:s.held.map(()=>false),shop:[],refreshes:0,status:'playing'}}
