import { CHARMS, TABLES, bestCategory, buy, doRoll, enterTable, evaluate, newRun, nextAnte, scoreHand, scoreTurn, skipShop, toggleHold, type Category, type RunState } from './engine';

export interface SimulationResult { seed: number; won: boolean; tableReached: number; totalScore: number; hands: number; rerolls: number; cash: number; charms: string[] }
function holdsFor(state: RunState): boolean[] { const counts = new Map<number, number>(); state.dice.forEach(d => counts.set(d, (counts.get(d) ?? 0) + 1)); const largest = [...counts.entries()].sort((a, b) => b[1] - a[1] || b[0] - a[0])[0]; if (largest && largest[1] >= 2) return state.dice.map(d => d === largest[0]); const unique = [...new Set(state.dice)].sort((a, b) => a - b); let best: number[] = []; for (let start = 1; start <= 3; start++) { const candidate = unique.filter(v => v >= start && v <= start + 3); if (candidate.length > best.length) best = candidate; } if (best.length >= 3) return state.dice.map(d => best.includes(d)); return state.dice.map(d => d >= 5); }
function bestScore(state: RunState): { category: Category; chips: number } { const categories = evaluate(state.dice); return categories.map(category => ({ category, chips: scoreHand(state.dice, category, state.charms, state.cash, state.rolls, state).chips })).sort((a, b) => b.chips - a.chips)[0] ?? { category: 'chance', chips: 0 }; }
const charmPriority = ['silver-pair', 'double-stitch', 'second-wind', 'brass-tack', 'three-bells', 'family-seal', 'even-keel', 'high-polish', 'house-lantern', 'held-breath', 'short-fuse', 'last-call', 'sequence-key', 'velvet-rope', 'long-gallery', 'loaded-ledger', 'rainy-purse', 'odd-job', 'small-favor', 'steady-hand', 'sixth-sense', 'low-road', 'fifth-pocket', 'echo-chamber', 'pocket-change', 'open-secret'];
function shopHeuristic(state: RunState): RunState { let next = state; const offers = [...next.shop].sort((a, b) => charmPriority.indexOf(a) - charmPriority.indexOf(b)); for (const id of offers) { const charm = CHARMS.find(c => c.id === id)!; if (next.charms.length < 5 && next.cash >= charm.cost) next = buy(next, id); } if (next.shop.length > 0 && !next.skippedShop) next = skipShop(next); return next; }
export function simulateRun(seed: number): SimulationResult { let state = newRun(seed); let guard = 0; while (guard++ < 300 && state.status !== 'won' && state.status !== 'lost') { if (state.status === 'briefing') { state = enterTable(state); continue; } if (state.status === 'shop') { state = nextAnte(shopHeuristic(state)); continue; } if (state.dice.length === 0) { state = doRoll(state); continue; } const candidate = bestScore(state); const needed = state.target - state.score; const scoreEarly = candidate.chips >= needed || (state.ante === 3 && candidate.chips >= 90); if (state.rolls > 0 && !scoreEarly) { const holds = holdsFor(state); holds.forEach((hold, index) => { if (hold !== state.held[index]) state = toggleHold(state, index); }); state = doRoll(state); continue; } state = scoreTurn(state, bestCategory(state.dice, state)); }
  return { seed, won: state.status === 'won', tableReached: state.stats.tableReached, totalScore: state.stats.totalScore, hands: state.stats.handsScored, rerolls: state.stats.rerolls, cash: state.cash, charms: state.charms };
}
export function runSimulation(count = 1000, firstSeed = 1) { const results = Array.from({ length: count }, (_, i) => simulateRun(firstSeed + i)); const reaches = TABLES.map((_, i) => results.filter(r => r.tableReached >= i + 1).length); const victories = results.filter(r => r.won).length; const totals = results.map(r => r.totalScore).sort((a, b) => a - b); return { runs: count, victories, victoryRate: victories / count, reaches, medianTotal: totals[Math.floor(count / 2)] ?? 0, p90Total: totals[Math.floor(count * .9)] ?? 0, averageHands: results.reduce((n, r) => n + r.hands, 0) / count, results }; }
